### ISSUE TITLE
Chapter 7, Listing 7.10 is missing `depends_on`

### ISSUE THREAD

**Issue by paulredmond** [bitpressio/docker-for-php-developers-errata#4]
In Chapter 7, listing `7.10` needs a `depends_on` key for the app image in the `cake` service:

```yaml
#...
  cake:
    image: cakephp-app
    container_name: cakephp-console
    depends_on:
      - app
    volumes:
      - .:/srv/cakephp
    entrypoint: [
      "/srv/cakephp/app/Console/cake",
      "-app", "/srv/cakephp/app"
    ]
```
